# Generated by Django 5.1.6 on 2025-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pro_seller',
            field=models.ManyToManyField(to='account.product_seller'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
