# Generated by Django 5.1.6 on 2025-04-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdetails',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ordersdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentord',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordersdetails',
            name='order_products',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Paymentord',
        ),
        migrations.DeleteModel(
            name='Ordersdetails',
        ),
    ]
